import mysql.connector
from mysql.connector import Error

DB_CONFIG = {
    'host': 'localhost',
    'user': 'root', #seu usuario 
    'password': '1910' #sua senha
}

def create_database_and_table():
    try:
        connection = mysql.connector.connect(**DB_CONFIG)
        
        if connection.is_connected():
            cursor = connection.cursor()
            
            cursor.execute("CREATE DATABASE IF NOT EXISTS covid_db")
            cursor.execute("USE covid_db")
            
            create_table_query = """
            CREATE TABLE IF NOT EXISTS covid_data (
                id INT AUTO_INCREMENT PRIMARY KEY,
                date DATE,
                city VARCHAR(100),
                confirmed INT,
                deaths INT,
                estimated_population INT,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
            """
            cursor.execute(create_table_query)
            
            print("Banco de dados e tabela criados com sucesso!")
            return True
            
    except Error as e:
        print(f"Erro ao criar banco de dados e tabela: {e}")
        return False
    finally:
        if connection.is_connected():
            cursor.close()
            connection.close()

if __name__ == "__main__":
    create_database_and_table()
